import type { Metadata } from "next";
import { Passion_One, Open_Sans } from "next/font/google";
import "./globals.css";

const passionOne = Passion_One({
  variable: "--font-passion-one",
  subsets: ["latin"],
  weight: ['400', '700']
});

const openSans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hive - Plataforma Digital",
  description: "Generated by create next app",
  authors: [
    { name: 'Ignacio Joaquín Pantoja' },
    { name: 'Paula Fuentes' }
  ],
  keywords: ["Diseño", "Proyecto", "Estudiante", "Unlar", "Documentos"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${passionOne.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
