export const depts = {
  "Ciencias Exactas, Físicas y Naturales": [
    "Bioquímica",
    "Farmacia",
    "Ingeniería en Sistemas de Información",
    "Licenciatura en Sistemas de Información",
    "Licenciatura en Diseño y Producción Multimedial",
    "Licenciatura en Ciencias Biológicas",
    "Ingeniería Mecatrónica",
    "Tecnicatura Universitaria en Informática",
    "Tecnicatura Universitaria en Biogenética"
  ],
  "Ciencias Humanas y de la Educación": [
    "Licenciatura en Letras",
    "Licenciatura en Lengua y Literatura Inglesa",
    "Licenciatura en Artes Plásticas",
    "Licenciatura en Historia",
    "Licenciatura en Música",
    "Licenciatura en Arte Escénico",
    "Licenciatura en Teología y Religiones Comparadas",
    "Licenciatura en Psicopedagogía",
    "Traductorado Público Nacional en Lengua Inglesa",
    "Licenciatura en Gestión Organizacional y Recursos Humanos",
    "Licenciatura en Ciencias de la Educación",
    "Profesorado Universitario en Historia para el Nivel Secundario y Superior",
    "Profesorado Universitario en Letras para el Nivel Secundario y Superior",
    "Profesorado Universitario en Lengua Inglesa",
    "Profesorado Universitario en Psicopedagogía"
  ],
  "Ciencias Sociales, Jurídicas y Económicas": [
    "Abogacía",
    "Escribanía",
    "Contador Público",
    "Licenciatura en Administración",
    "Licenciatura en Economía",
    "Licenciatura en Ciencia Política",
    "Licenciatura en Turismo",
    "Licenciatura en Comunicación Social",
    "Licenciatura en Trabajo Social",
    "Licenciatura en Criminalística",
    "Tecnicatura Universitaria en Gestión Jurídica",
    "Tecnicatura Universitaria en Gestión y Administración Contable",
    "Tecnicatura Universitaria en Subastador y Martillero Público",
    "Tecnicatura Universitaria en Tasador y Corredor Inmobiliario",
    "Tecnicatura Universitaria en Guía de Turismo",
    "Tecnicatura Universitaria en Seguridad Urbana",
    "Tecnicatura Universitaria en Televisión Digital"
  ],
  "Aplicadas": [
    "Arquitectura",
    "Geología",
    "Ingeniería Industrial",
    "Ingeniería Civil",
    "Ingeniería Agroindustrial",
    "Ingeniería en Minas",
    "Ingeniería en Alimentos",
    "Ingeniería Agronómica",
    "Tecnicatura Universitaria Agrícola",
    "Tecnicatura Universitaria en Minería",
    "Tecnicatura Universitaria en Tecnología de los Alimentos"
  ],
  "Sociales": [
    "Abogacía",
    "Escribanía",
    "Contador Público",
    "Licenciatura en Administración",
    "Licenciatura en Economía",
    "Licenciatura en Ciencia Política",
    "Licenciatura en Turismo",
    "Licenciatura en Comunicación Social",
    "Licenciatura en Trabajo Social",
    "Licenciatura en Criminalística"
  ],
  "Ciencias de la Salud": [
    "Medicina",
    "Odontología",
    "Enfermería Universitaria",
    "Licenciatura en Enfermería",
    "Licenciatura en Producción de Bioimágenes",
    "Licenciatura en Terapia Ocupacional"
  ]
};